= Saga implemetations comparison
Martin Stefanko <xstefank122@gmail.com>
v1.0, 2017-11-26
ifndef::imagesdir[:imagesdir: images]
:sourcedir: src/main/java

== Saga implemetations comparison

In this previous http://jbossts.blogspot.cz/2017/06/sagas-and-how-they-differ-from-two.html[blog post]
we have investigated the genaral motions of the https://www.cs.cornell.edu/andru/cs711/2002fa/reading/sagas.pdf[saga pattern]
and how sagas differ from traditional ACID approach.
This article will focus on the current state of applicability of
this pattern. We will introduce, describe and compare three frameworks
that presently support saga processing, namely Narayana LRA,
Axon framework and Eventuate.io.

=== Narayana LRA

Narayana Long Running Actions is a specification developed by the Narayana team
in collaboration with the Eclipse MicroProfile initiative. The main focus is to
introduce an API for coordinating long running activities with the assurance
of the globally consistent outcome and without any locking mechanisms.

[\https://github.com/eclipse/microprofile-sandbox/tree/master/proposals/0009-LRA]


=== Axon framework

Axon framework is Java based framework for building
scalable and highly performant applications. Axon is based on Command Query
Responsibility Segregation (https://martinfowler.com/bliki/CQRS.html[CQRS])
pattern. The main motion is the event processing which includes separated Command bus
for updates and Event bus for queries.

[\http://www.axonframework.org/]


=== Eventuate.io

Eventuate is a platform that provides event-driven programming model that focus
on solving distributed data management in microservices architectures. Similarly
to the Axon, it is based upon CQRS principles. The framework stores events
in the MySQL database and it distributes them through the Apache Kafka plarform.

[\http://eventuate.io]

NOTE: CQRS is an architectural pattern that splits the domain model into two separated
      areas - the first one is responsible for updates and containing business logic
      while the other is taking care of the reads and providing information for the user

== Comparisons

Even through all of the above frameworks achieve the same outcome there are
several areas where we can examine how the handling of the saga processing differ.



=== Developer friendliness

The LRA provides for the developer traditional coordinator oriented architecture.
Individual participants can join the LRA by the HTTP call to the LRA coordinator, each
providing methods for saga completion and compensation. Narayana provides a LRA client
which makes the REST invocations transparent.

In the Axon sagas are implemented as aggregates. The aggregate is a logical group of
entities and value objects that are treated as a single unit. Axon uses special type of
event listener that allows the developer to associate a property in the events with
the current saga so that the framework knows which saga should be invoked. The invocation
and compensation are executed by separated event handler and therefore a different events.

Not a long ago Eventuate presented a new API called Eventuate Tram which handles the saga
processing for the platform. It enables applications to send messages as a part of
an database transaction. The platform provides abstractions for messaging in form of named
channels, events as subscriptions to domain events and commands for asynchronous
communication.

==== Saga specifications

In the LRA the specification of how the saga should be performed is specified at the
initiator. Initiating service is able to invoke participants on the provided endpoints
which allows participant to join the LRA context. The participant can specify whether to
join, create new or ignore the corresponding LRA context by the CDI annotation.

Axon provides a set of annotation the denote the saga class. A @Saga annotation defines
the class as a saga aggregate which allows it do declare a saga event handlers. Saga
handler can optionally include the name of the property in the incoming event which
has been previously associated with the saga. Additionally Axon provides special annotations
to mark the start and stop of the saga.

In Eventuate the developer is able to specify the saga definition including the participant
invocation, compensation and reply handlers by the saga definition. It provides a simple
builder which constructs the saga step by step providing the handlers for command and event
 processing.

=== Failure recovery

The saga compensating actions are in the LRA defined as a designated endpoints. The
participants registers with the LRA with its base address. If the initiating service then
cancels the LRA, the coordinator is able to call the compensation endpoints of the included
participants.

In Axon application developers need to know which events represents the failure. Also the
tracking of the progress as well as of the compensation is handled by the developer.

Eventuate registers the compensation handlers in the saga definitions. Participants are
allowed to send a special command which indicates failure a therefore the compensation of
the previous actions.

=== Structure

=== Blocking and synchronization

=== Idempotency



