= Saga implemetations comparison
Martin Stefanko <xstefank122@gmail.com>
v1.0, 2017-11-26
ifndef::imagesdir[:imagesdir: images]
:sourcedir: src/main/java

== Saga implemetations comparison

In this previous http://jbossts.blogspot.cz/2017/06/sagas-and-how-they-differ-from-two.html[blog post]
we have investigated the genaral motions of the https://www.cs.cornell.edu/andru/cs711/2002fa/reading/sagas.pdf[saga pattern]
and how sagas differ from traditional ACID approach.
This article will focus on the current state of applicability of
this pattern. We will introduce, describe and compare three frameworks
that presently support saga processing, namely Narayana LRA,
Axon framework and Eventuate.io.

Let me start with a short introduction to the mentioned frameworks.

=== Narayana LRA

Narayana Long Running Actions is a specification developed by the Narayana team
in collaboration with the Eclipse MicroProfile initiative. The main focus is to
introduce an API for coordinating long running activities with the assurance
of the globally consistent outcome and without any locking mechanisms.

[\https://github.com/eclipse/microprofile-sandbox/tree/master/proposals/0009-LRA]


=== Axon framework

Axon framework is Java based framework for building
scalable and highly performant applications. Axon is based on Command Query
Responsibility Segregation (https://martinfowler.com/bliki/CQRS.html[CQRS])
pattern. Axon is based on event processing which includes separated Command bus for
updates and Event bus for queries.

[\http://www.axonframework.org/]


=== Eventuate.io

Eventuate is a platform that provides event-driven programming model that focus
on solving distributed data management in microservices architectures. Similarly
to the Axon, it is based upon CQRS principles. The platform stores events
in the MySQL database and it distributes them through the Apache Kafka.

[\http://eventuate.io]

NOTE: CQRS is an architectural pattern that splits the domain model into two separated
      areas - the first one is responsible for updates and containing business logic
      while the other taking care of the reads and providing information for the user

== Comparisons

Even through all of the above frameworks achieve the same outcome there are
several areas where we can examine how the handling of the saga processing differ.



=== Developer friendliness

The LRA provides for the developer traditional coordinator oriented architecture. Individual
participants can join the LRA by the HTTP call to the LRA coordinator, each providing methods
for saga completion and compensation.

In the Axon sagas are impleted as aggregates. The aggregate is a logical group of entities
and value objects that are treated as a single unit. Axon uses special type of event listener
that allows the developer to associate a value in the events with the current saga so that
the framework knows which saga should be invoked.

By the time of this writing Eventuate come out with a new Saga API which I still need to
investigate. Before that, the whole saga manipulation was up to the developers implementation.
footnote:[in the basic approach it is worth noting that Eventuate platform creates
aggregates by the default constructor calls which causes prolems with DI] Both Eventuate
and Axon handle saga completion and compenstation by separate event handlers.

